### ISSUE TITLE
Adding Synamp2 output to reformat.syntenyData

### ISSUE THREAD

**Issue by DustinSokolowski** [Farre-lab/syntenyPlotteR#3]
Hey!

This is a really exciting-looking tool. I was wondering if you were considering adding the Synmap2 output to the reformat.syntenyData function? 

Thanks!
Dustin

**Comment by Squigley18** [comment]
Hi Dustin, 

Thank you for bringing this to our attention. So far there are a few tools we intend to begin working on to allow for reformatting data; particularly tools such as mcscan. We will ad this to considerations for development 

Thank you for informing us of this tool. 

Best wishes 

Sarah Q
