### ISSUE TITLE
Ideogram not getting colored

### ISSUE THREAD

**Issue by trihim** [Farre-lab/syntenyPlotteR#8]
Hi I am able to run both draw.ideogram and draw.linear commands, but not able to color the ideogram. The reference panel on the side is colored, and syntenic blocks are also visible. Just the syntenic blocks are not colored. I am attaching the file 
![Synteny_error](https://github.com/user-attachments/assets/38eb0f56-df31-405d-b66d-f7258d42c83a)

**Comment by marta-fb** [comment]
Hi,

Could you please past a snippet of your input data?

Thanks
Marta

**Comment by trihim** [comment]
Sure. Here is head for synteny data 

1	132671951	132710791	chr10	21514603	21554171	+	Lemur	CHM13
1	207128296	207162385	chr3	184501814	184536188	+	Lemur	CHM13
1	72384236	72414088	chr15	34878587	34908277	+	Lemur	CHM13
1	72199356	72225216	chr15	34684952	34710619	+	Lemur	CHM13
1	230110189	230139177	chr3	117034769	117064049	-	Lemur	CHM13

And here is for size file

1	286674946	Lemur
2	147489633	Lemur
3	126926352	Lemur
4	117448925	Lemur
5	114043961	Lemur
.
.
.
.
chr20	66210255	CHM13
chr21	45090682	CHM13
chr22	51324926	CHM13

**Comment by trihim** [comment]
Hi any comments to resolve the issue?

**Comment by Squigley18** [comment]
Hi,

The file format seems to be fine from first look. I am unable to run this data myself from this subset so for the moment I have a suggestion I think may help. 

I would consider checking  that the chromosome names exactly match the chromosome names used to change the colours as I believe you have manually changed the colours here? 
For example do you have "chr 1" in one and just the number 1 in the other? It may help to have consistent chromosome identifiers, either have only the chromosome numerical value or the full "chr 1" for both species in the data file and length file as it can be easier to keep track of in this case. 

If this is still not working, then it may be the case that I will need to get the data files you ran and the exact inputs you provided to the function to have a more detailed look.

**Comment by trihim** [comment]
Hi, yes that numbering was the issue and it got resolved. Thanks!
